extern const GeoLayout mario_maker_laugh_geo[];
extern u8 mario_maker_laugh_pink_rgba16[];
extern u8 mario_maker_laugh_blue_rgba16[];
extern u8 mario_maker_laugh_yellow_rgba16[];
extern Vtx mario_maker_laugh_LaughSprite_LaughSprite_mesh_layer_4_mario_vtx_0[4];
extern Gfx mario_maker_laugh_LaughSprite_LaughSprite_mesh_layer_4_mario_tri_0[];
extern Vtx mario_maker_laugh_LaughSprite_LaughSprite_mesh_layer_4_mario_vtx_1[4];
extern Gfx mario_maker_laugh_LaughSprite_LaughSprite_mesh_layer_4_mario_tri_1[];
extern Gfx mat_mario_maker_laugh_pink_Icon_mario[];
extern Gfx mat_mario_maker_laugh_blue_Icon_mario[];
extern Gfx mat_mario_maker_laugh_yellow_Icon_mario[];
extern Gfx mat_revert_mario_maker_laugh_LaughSprite_Icon[];
extern Gfx mario_maker_laugh_pink_mesh_layer_4_mario[];
extern Gfx mario_maker_laugh_blue_mesh_layer_4_mario[];
extern Gfx mario_maker_laugh_yellow_mesh_layer_4_mario[];
extern Gfx mario_maker_laugh_material_revert_render_settings[];
