extern const GeoLayout sl_area_1_geo[];
extern const GeoLayout sl_area_1[];
extern const Collision sl_area_1_collision[];
extern const MacroObject sl_area_1_macro_objs[];
extern const GeoLayout sl_area_2_geo[];
extern const GeoLayout sl_area_2[];
extern const Collision sl_area_2_collision[];
extern const MacroObject sl_area_2_macro_objs[];
extern u8 sl_dl_nadtiles_ci8[];
extern u8 sl_dl_nadtiles_pal_rgba16[];
extern u8 sl_dl_greenfog_ia8[];
extern u8 sl_dl_personatiles_ci8[];
extern u8 sl_dl_personatiles_pal_rgba16[];
extern u8 sl_dl_personalinedecal_ci8[];
extern u8 sl_dl_personalinedecal_pal_rgba16[];
extern u8 sl_dl_personawheel_rgba16[];
extern u8 sl_dl_ppillar_ci8[];
extern u8 sl_dl_ppillar_pal_rgba16[];
extern u8 sl_dl_bloob_ci4[];
extern u8 sl_dl_bloob_pal_rgba16[];
extern u8 sl_dl_pillar_ci4[];
extern u8 sl_dl_pillar_pal_rgba16[];
extern Vtx sl_dl_Plane_mesh_layer_1_vtx_0[22];
extern Gfx sl_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Circle_mesh_layer_1_vtx_0[78];
extern Gfx sl_dl_Circle_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Plane_001_mesh_layer_1_vtx_0[32];
extern Gfx sl_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx sl_dl_Plane_001_mesh_layer_1_vtx_1[228];
extern Gfx sl_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx sl_dl_Plane_001_mesh_layer_1_vtx_2[636];
extern Gfx sl_dl_Plane_001_mesh_layer_1_tri_2[];
extern Vtx sl_dl_Plane_001_mesh_layer_2_vtx_0[40];
extern Gfx sl_dl_Plane_001_mesh_layer_2_tri_0[];
extern Vtx sl_dl_Plane_001_mesh_layer_6_vtx_0[4];
extern Gfx sl_dl_Plane_001_mesh_layer_6_tri_0[];
extern Vtx sl_dl_Plane_001_mesh_layer_6_vtx_1[8];
extern Gfx sl_dl_Plane_001_mesh_layer_6_tri_1[];
extern Gfx mat_sl_dl_f3dlite_material_001[];
extern Gfx mat_revert_sl_dl_f3dlite_material_001[];
extern Gfx mat_sl_dl_f3dlite_material_010[];
extern Gfx mat_revert_sl_dl_f3dlite_material_010[];
extern Gfx mat_sl_dl_f3dlite_material_002[];
extern Gfx mat_revert_sl_dl_f3dlite_material_002[];
extern Gfx mat_sl_dl_f3dlite_material_004[];
extern Gfx mat_revert_sl_dl_f3dlite_material_004[];
extern Gfx mat_sl_dl_f3dlite_material_005[];
extern Gfx mat_revert_sl_dl_f3dlite_material_005[];
extern Gfx mat_sl_dl_f3dlite_material_006[];
extern Gfx mat_revert_sl_dl_f3dlite_material_006[];
extern Gfx mat_sl_dl_f3dlite_material_008[];
extern Gfx mat_revert_sl_dl_f3dlite_material_008[];
extern Gfx mat_sl_dl_f3dlite_material_009[];
extern Gfx mat_revert_sl_dl_f3dlite_material_009[];
extern Gfx sl_dl_Plane_mesh_layer_1[];
extern Gfx sl_dl_Circle_mesh_layer_1[];
extern Gfx sl_dl_Plane_001_mesh_layer_1[];
extern Gfx sl_dl_Plane_001_mesh_layer_2[];
extern Gfx sl_dl_Plane_001_mesh_layer_6[];
extern Gfx sl_dl_material_revert_render_settings[];
