#include "src/game/envfx_snow.h"

const GeoLayout fazana_car_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, fazana_car_Body_mesh_layer_1),
		// GEO_ASM(0, car_front_wheels),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 2, 8, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, fazana_car_Front_Wheel_DL_mesh_layer_4),
		GEO_CLOSE_NODE(),
		// GEO_ASM(0, car_left_door),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 6, 3, 4, 0, 0, 0),
		// GEO_ASM(0, car_rear_wheels),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 0, 2, -7, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, fazana_car_Rear_Wheel_DL_mesh_layer_4),
		GEO_CLOSE_NODE(),
		// GEO_ASM(0, car_right_door),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, -6, 4, 4, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, fazana_car_Left_Door_ZDL_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, fazana_car_Right_Door_ZDL_mesh_layer_1),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, fazana_car_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, fazana_car_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
