extern const GeoLayout title_sponge_geo[];
extern u8 title_sponge_dma2_rgba16[];
extern u8 title_sponge_dmatex_rgba16[];
extern Vtx title_sponge_Plane_004_mesh_layer_1_vtx_0[4];
extern Gfx title_sponge_Plane_004_mesh_layer_1_tri_0[];
extern Vtx title_sponge_Plane_004_mesh_layer_1_vtx_1[4];
extern Gfx title_sponge_Plane_004_mesh_layer_1_tri_1[];
extern Gfx mat_title_sponge_bottom[];
extern Gfx mat_title_sponge_top[];
extern Gfx title_sponge_Plane_004_mesh_layer_1[];
extern Gfx title_sponge_material_revert_render_settings[];
