extern const GeoLayout png_gun_geo[];
extern Lights1 png_gun_png_gun_lights;
extern u8 png_gun_png_gun_ci4[];
extern u8 png_gun_png_gun_ci4_pal_rgba16[];
extern Vtx png_gun_png_gun_sprite_mesh_layer_4_vtx_0[4];
extern Gfx png_gun_png_gun_sprite_mesh_layer_4_tri_0[];
extern Gfx mat_png_gun_png_gun[];
extern Gfx mat_revert_png_gun_png_gun[];
extern Gfx png_gun_png_gun_sprite_mesh_layer_4[];
extern Gfx png_gun_material_revert_render_settings[];
