extern const GeoLayout hmc_area_1_geo[];
extern const GeoLayout hmc_area_1[];
extern const Collision hmc_area_1_collision[];
extern const MacroObject hmc_area_1_macro_objs[];
extern u8 hmc_dl_carquest_ground_rgba16[];
extern u8 hmc_dl_carquest_ground_ia8[];
extern u8 hmc_dl_sand_rgba16[];
extern Vtx hmc_dl_Plane_001_mesh_layer_1_vtx_0[51];
extern Gfx hmc_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx hmc_dl_Plane_001_mesh_layer_1_vtx_1[87];
extern Gfx hmc_dl_Plane_001_mesh_layer_1_tri_1[];
extern Vtx hmc_dl_Plane_001_mesh_layer_1_vtx_2[13];
extern Gfx hmc_dl_Plane_001_mesh_layer_1_tri_2[];
extern Gfx mat_hmc_dl_f3dlite_material_003[];
extern Gfx mat_revert_hmc_dl_f3dlite_material_003[];
extern Gfx mat_hmc_dl_f3dlite_material_006[];
extern Gfx mat_revert_hmc_dl_f3dlite_material_006[];
extern Gfx mat_hmc_dl_f3dlite_material_008[];
extern Gfx mat_revert_hmc_dl_f3dlite_material_008[];
extern Gfx hmc_dl_Plane_001_mesh_layer_1[];
extern Gfx hmc_dl_material_revert_render_settings[];
