COURSE_ACTS(COURSE_BOB, _(" 1 BOB-OMB BATTLEFIELD"),
       _("BIG BOB-OMB ON THE SUMMIT")     , _("FOOTRACE WITH KOOPA THE QUICK") , _("SHOOT TO THE ISLAND IN THE SKY"),
       _("FIND THE 8 RED COINS")          , _("MARIO WINGS TO THE SKY")        , _("BEHIND CHAIN CHOMP'S GATE"))

COURSE_ACTS(COURSE_WF, _(" 2 TROL LLEVE"),
       _("HAHA LOL"), _("HAHA LOL"), _("HAHA LOL"),
       _("HAHA LOL"), _("HAHA LOL"), _("HAHA LOL"))

COURSE_ACTS(COURSE_JRB, _(" 3 JOLLY ROGER BAY"),
       _("PLUNDER IN THE SUNKEN SHIP")    , _("CAN THE EEL COME OUT TO PLAY?") , _("TREASURE OF THE OCEAN CAVE"),
       _("RED COINS ON THE SHIP AFLOAT")  , _("BLAST TO THE STONE PILLAR")     , _("THROUGH THE JET STREAM"))

COURSE_ACTS(COURSE_CCM, _(" 4 h"),
       _("i"), _("i"), _("i"),
       _("i"), _("i"), _("i"))

COURSE_ACTS(COURSE_BBH, _(" 5 LOL CAN U READ TIHS"),
       _("JUST POUND HTHE TWOMPS"), _("JUST POUND HTHE TWOMPS"), _("JUST POUND HTHE TWOMPS"),
       _("JUST POUND HTHE TWOMPS"), _("JUST POUND HTHE TWOMPS"), _("JUST POUND HTHE TWOMPS"))

COURSE_ACTS(COURSE_HMC, _(" 6 CAR QUEST"),
       _("TOTALLY NOT A BOOTLEG"), _("TOTALLY NOT A BOOTLEG"), _("TOTALLY NOT A BOOTLEG"),
       _("TOTALLY NOT A BOOTLEG"), _("TOTALLY NOT A BOOTLEG"), _("TOTALLY NOT A BOOTLEG"))

COURSE_ACTS(COURSE_LLL, _(" 7 LETHAL LAVA LAND"),
       _("BOIL THE BIG BULLY")            , _("BULLY THE BULLIES")             , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 THEE ENDLES VOID"),
       _("BUT WITH HOUSSES :D"), _("BUT WITH HOUSSES :D"), _("BUT WITH HOUSSES :D"),
       _("BUT WITH HOUSSES :D"), _("BUT WITH HOUSSES :D"), _("BUT WITH HOUSSES :D"))

COURSE_ACTS(COURSE_DDD, _(" 9 DIRE, DIRE DOCKS"),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 PURSE"),
       _("OWN A TREE"), _("OWN A TREE"), _("OWN A TREE"),
       _("OWN A TREE"), _("OWN A TREE") , _("OWN A TREE"))

COURSE_ACTS(COURSE_WDW, _("11 WET-DRY WORLD"),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 TALL, TALL MOUNTAIN"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 TINY-HUGE ISLAND"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 GLAGGLELAND"),
       _("ENABLE FRAMEBUFFER EMULATION"), _("ENABLE FRAMEBUFFER EMULATION"), _("ENABLE FRAMEBUFFER EMULATION"),
       _("ENABLE FRAMEBUFFER EMULATION"), _("ENABLE FRAMEBUFFER EMULATION"), _("ENABLE FRAMEBUFFER EMULATION"))

COURSE_ACTS(COURSE_RR, _("15 THE FINAALLEVEL"),
       _("NO DIE"), _("NO DIE"), _("NO DIE"),
       _("NO DIE"), _("NO DIE"), _("NO DIE"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER IN THE DARK WORLD"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER IN THE FIRE SEA"))
SECRET_STAR(COURSE_BITS, _("   BOWSER IN THE SKY"))
SECRET_STAR(COURSE_PSS, _("   THE PRINCESS'S SECRET SLIDE"))
SECRET_STAR(COURSE_COTMC, _("   CAVERN OF THE METAL CAP"))
SECRET_STAR(COURSE_TOTWC, _("   TOWER OF THE WING CAP"))
SECRET_STAR(COURSE_VCUTM, _("   VANISH CAP UNDER THE MOAT"))
SECRET_STAR(COURSE_WMOTR, _("   WING MARIO OVER THE RAINBOW"))
SECRET_STAR(COURSE_SA, _("   THE SECRET AQUARIUM"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("         ROBUX"))

EXTRA_TEXT(0, _("ONE OF THE CASTLE'S SECRET STARS!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
