extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_f3dlite_material_002_lights;
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[190];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[9];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_002[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
