extern const GeoLayout wf_area_1_geo[];
extern const GeoLayout wf_area_1[];
extern const Collision wf_area_1_collision[];
extern const MacroObject wf_area_1_macro_objs[];
extern const GeoLayout wf_area_2_geo[];
extern const GeoLayout wf_area_2[];
extern const Collision wf_area_2_collision[];
extern const MacroObject wf_area_2_macro_objs[];
extern const GeoLayout wf_area_3_geo[];
extern const GeoLayout wf_area_3[];
extern const Collision wf_area_3_collision[];
extern const MacroObject wf_area_3_macro_objs[];
extern Lights1 wf_dl_f3dlite_material_lights;
extern Lights1 wf_dl_f3dlite_material_001_lights;
extern Lights1 wf_dl_f3dlite_material_003_lights;
extern Lights1 wf_dl_f3dlite_material_007_lights;
extern Lights1 wf_dl_f3dlite_material_006_lights;
extern Lights1 wf_dl_f3dlite_material_008_lights;
extern Lights1 wf_dl_f3dlite_material_004_lights;
extern Lights1 wf_dl_f3dlite_material_009_lights;
extern u8 wf_dl_ecksdee_i8[];
extern u8 wf_dl_RMGP01_362bb7be_14_ci8[];
extern u8 wf_dl_RMGP01_362bb7be_14_pal_rgba16[];
extern u8 wf_dl_RMGP01_69c33ad1_14_ci4[];
extern u8 wf_dl_RMGP01_69c33ad1_14_pal_rgba16[];
extern Vtx wf_dl_Plane_mesh_layer_1_vtx_0[190];
extern Gfx wf_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_001_mesh_layer_1_vtx_0[9];
extern Gfx wf_dl_Plane_001_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_0[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_1[26];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_1[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_2[160];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_2[];
extern Vtx wf_dl_Plane_003_mesh_layer_1_vtx_3[4];
extern Gfx wf_dl_Plane_003_mesh_layer_1_tri_3[];
extern Vtx wf_dl_Plane_004_mesh_layer_1_vtx_0[67];
extern Gfx wf_dl_Plane_004_mesh_layer_1_tri_0[];
extern Vtx wf_dl_Plane_006_mesh_layer_1_vtx_0[8];
extern Gfx wf_dl_Plane_006_mesh_layer_1_tri_0[];
extern Gfx mat_wf_dl_f3dlite_material[];
extern Gfx mat_revert_wf_dl_f3dlite_material[];
extern Gfx mat_wf_dl_f3dlite_material_001[];
extern Gfx mat_wf_dl_f3dlite_material_003[];
extern Gfx mat_wf_dl_f3dlite_material_007[];
extern Gfx mat_revert_wf_dl_f3dlite_material_007[];
extern Gfx mat_wf_dl_f3dlite_material_006[];
extern Gfx mat_wf_dl_f3dlite_material_008[];
extern Gfx mat_revert_wf_dl_f3dlite_material_008[];
extern Gfx mat_wf_dl_f3dlite_material_004[];
extern Gfx mat_wf_dl_f3dlite_material_009[];
extern Gfx mat_revert_wf_dl_f3dlite_material_009[];
extern Gfx wf_dl_Plane_mesh_layer_1[];
extern Gfx wf_dl_Plane_001_mesh_layer_1[];
extern Gfx wf_dl_Plane_003_mesh_layer_1[];
extern Gfx wf_dl_Plane_004_mesh_layer_1[];
extern Gfx wf_dl_Plane_006_mesh_layer_1[];
extern Gfx wf_dl_material_revert_render_settings[];
