extern const GeoLayout troll_water_geo[];
extern Lights1 troll_water_f3dlite_material_003_lights;
extern u8 troll_water_RMGP01_34bcf116_14_ci4[];
extern u8 troll_water_RMGP01_34bcf116_14_pal_rgba16[];
extern Vtx troll_water_Plane_001_mesh_layer_5_vtx_0[4];
extern Gfx troll_water_Plane_001_mesh_layer_5_tri_0[];
extern Gfx mat_troll_water_f3dlite_material_003[];
extern Gfx mat_revert_troll_water_f3dlite_material_003[];
extern Gfx troll_water_Plane_001_mesh_layer_5[];
extern Gfx troll_water_material_revert_render_settings[];
